SP/src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Table(name="`service`")
 * @ORM\Entity
 * @UniqueEntity(fields="name", message="This service is already created")
 */
class Service
{
    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="Service")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $ruler;

    /**
     * @param mixed $ruler
     */
    public function setRuler($ruler)
    {
        $this->ruler = $ruler;
    }
    public function getRuler()
    {
        return $this->ruler;
    }
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=191, unique=true)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="float", length=6)
     * @Assert\NotBlank()
     * @Assert\Range(
     *     min = 0.1,
     *     minMessage = "Price should not be less than 0.1"
     * )
     */
    private $price;

    /**
     * @ORM\Column(type="float", length=3)
     * @Assert\NotBlank()
     * @Assert\Range(
     *     min = 0.1,
     *     minMessage = "Duration can not be less than 0.1 hour"
     * )
     */
    private $duration;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     * @Assert\Range(
     *     min = 1,
     *     max = 100,
     *     minMessage = "Discount should not be less than 1%",
     *     maxMessage = "Discount should not be more than 100%"
     * )
     */
    private $discount;
    /**
     **  @ORM\Column(type="float", length=10, nullable=true)
     */
    private $totalPrice;

    public function getId()
    {
        return $this->id;
    }
    public function getName()
    {
        return $this->name;
    }
    public function setName($name)
    {
        $this->name = $name;
    }
    public function getPrice()
    {
        return $this->price;
    }
    public function setPrice($price)
    {
        $this->price = $price;
    }
    public function getDuration()
    {
        return $this->duration;
    }
    public function setDuration($duration)
    {
        $this->duration = $duration;
    }
    public function getDiscount()
    {
        return $this->discount;
    }
    public function setDiscount($discount)
    {
        $this->discount = $discount;
    }
    public function getTotalprice()
    {
        return $this->totalPrice;
    }
    public function setTotalPrice($price)
    {
        $this->totalPrice = $price;
    }
    public function __toString() {
        return (string) $this->name . ' '. "(" . (string) $this->totalPrice . "€)";
    }
}

SP/src/Form/ServiceType.php
<?php

namespace App\Form;

use App\Entity\Service;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('price', MoneyType::class)
            ->add('duration', NumberType::class)
            ->add('discount', IntegerType::class, array(
                'required' => false
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Service::class,
        ]);
    }
}

SP/src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Entity\User;
use App\Form\ServiceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class ServiceController extends Controller
{
    /**
     * @Route("/serviceregistration", name="serviceregistration")
     */
   public function CreateService(Request $request, AuthorizationCheckerInterface $authorizationChecker)
   {
       if ($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
           if ($this->getUser()->getisActive() == 1 && $this->getUser()->getRole() == 2) {
               $service = new Service();
               $user = $this->getUser();
               $service->setRuler($user);
               $form = $this->createForm(ServiceType::class, $service);

               $form->handleRequest($request);
               if ($form->isSubmitted() && $form->isValid()) {
                   $entityManager = $this->getDoctrine()->getManager();
                   $getTotalPrice = $service->getPrice() * ($service->getDiscount() / 100);
                   $service->setTotalPrice($service->getPrice() - $getTotalPrice);
                   $entityManager->persist($service);
                   $entityManager->flush();
                   return $this->redirectToRoute('service');
               }
           } else if (!$authorizationChecker->isGranted('ROLE_ADMIN')) {
               return $this->render(
                   'main/index.html.twig',
                   array('error' => 'You do not have permissions to enter this',
                   ));
           }


           return $this->render(
               'service/registration.html.twig',
               array('form' => $form->createView(),
                   )
           );
       }
       else
       {
           return $this->render(
               'main/index.html.twig',
               array('error' => 'You do not have permissions to enter this',
               ));
       }
   }

    /**
     * @Route("/serviceedit/{id}", name="serviceedit")
     */
   public function EditService($id, Request $request)
   {
       if($this->getUser()->getRole() == 2) {
           $service = $this->getDoctrine()->getRepository(Service::class)->findOneBy(['id' => $id]);
           $em = $this->getDoctrine()->getManager();

           if (!$service) {
               return $this->render(
                   'profile/index.html.twig',
                   array('error' => 'No service with this ID found',
                   ));
           }

           $form = $this->createForm(ServiceType::class, $service);
           $form->handleRequest($request);

           if ($form->isSubmitted() && $form->isValid()) {
               $getTotalPrice = $service->getPrice() * ($service->getDiscount() / 100);
               $service->setTotalPrice($service->getPrice() - $getTotalPrice);
               $em->flush();

               return $this->redirectToRoute('service');
           }
       }

       return $this->render(
           'service/registration.html.twig',
           array('form' => $form->createView(),
               'error' => 'No service with this ID found',
               'service' => $service,
           ));
   }

    /**
     * @Route("/service", name="service")
     */
   public function ShowServices()
   {
       if($this->getUser()->getisDisabled() == 1){
           return $this->render(
               'main/index.html.twig',
               array('error' => 'Your account is disabled. Please contact administrator for more information',
               ));
       }
       $service = $this->getDoctrine()->getRepository(Service::class)->findAll();

       return $this->render('service/index.html.twig', [
           'controller_name' => 'ServiceController',
           'services' => $service,
       ]);
   }

    /**
     * @Route("/servicedelete/{id}", name="servicedelete")
     */
   public function DeleteService($id, Request $request)
   {
       if($this->getUser()->getRoles() == 2) {
           $service = $this->getDoctrine()->getRepository(Service::class)->findOneBy(['id' => $id]);
           if ($service) {
               $em = $this->getDoctrine()->getManager();
               $em->remove($service);
               $em->flush();
           }
       }
       return $this->redirectToRoute('service');
   }
}

SP/templates/service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello!{% endblock %}

{% block body %}
    {% if app.user.role == 1 %}
        <style>
            .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
            .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        </style>
        {% if services is empty%}
        <div class="container-fluid" style="padding-top:250px; padding-bottom: 60px; ">
            {% if error is defined and error is not empty %}
                <div>  {{ error }} </div>
            {% endif %}
            {% if success is defined and success is not empty %}
                <div>  {{ success }} </div>
            {% endif %}
            <div class="text-left col-md-8 col-md-offset-2 ">
                <table id="services">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Duration</th>
                    <th>Discount</th>
                </tr>
                {% for s in services %}
                    <tr>
                        <td>{{ s.name }}</td>
                        <td>{{ s.price }}</td>
                        <td>{{ s.duration }}</td>
                        <td>{% if s.discount is null  %}
                                None
                            {% else %}
                                {{ s.discount }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
        {% else %}
        <div class="container-fluid padd">
            {% if error is defined and error is not empty %}
                <div>  {{ error }} </div>
            {% endif %}
            {% if success is defined and success is not empty %}
                <div>  {{ success }} </div>
            {% endif %}
            <div class="text-left col-md-8 col-md-offset-2 ">
                <table id="services">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Duration</th>
                    <th>Discount</th>
                </tr>
                {% for s in services %}
                    <tr>
                        <td>{{ s.name }}</td>
                        <td>{{ s.price }}</td>
                        <td>{{ s.duration }}</td>
                        <td>{% if s.discount is null  %}
                                None
                            {% else %}
                                {{ s.discount }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
        {% endif %}
    {% endif %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div>
    {% if app.user.role == 2 %}
        {% if error is defined and error is not empty %}
            <div>  {{ error }} </div>
        {% endif %}
        {% if success is defined and success is not empty %}
            <div>  {{ success }} </div>
        {% endif %}
        {% if services is empty%}
        <div class="container-fluid" style="padding-top:250px; padding-bottom: 60px;">
            {% if error is defined and error is not empty %}
                <div>  {{ error }} </div>
            {% endif %}
            {% if success is defined and success is not empty %}
                <div>  {{ success }} </div>
            {% endif %}
            <div class="text-left col-md-8 col-md-offset-2 ">
                <table id="services">
            <tr>
                <th>Created by</th>
                <th>Name</th>
                <th>Price</th>
                <th>Duration</th>
                <th>Discount</th>
                <th>Total price</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            {% for s in services %}
                <tr>
                    <td>{{ s.ruler }}</td>
                    <td>{{ s.name }}</td>
                    <td>{{ s.price }}</td>
                    <td>{{ s.duration }}</td>
                    <td>{% if s.discount is null  %}
                            None
                        {% else %}
                            {{ s.discount }}
                        {% endif %}
                    </td>
                    <td>{{ s.totalprice }}</td>
                    <td><a href = "{{ 'serviceedit/' ~ s.id }}">Edit</a></td>
                    <td><a href = "{{ 'servicedelete/' ~ s.id }}">Delete</a></td>
                </tr>
            {% endfor %}
                </table>
            </div>
        </div>
        {% else %}
        <div class="container-fluid padd">
            <div class="text-left col-md-8 col-md-offset-2 ">
                <table id="services">
            <tr>
                <th>Created by</th>
                <th>Name</th>
                <th>Price</th>
                <th>Duration</th>
                <th>Discount</th>
                <th>Total price</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            {% for s in services %}
                <tr>
                    <td>{{ s.ruler }}</td>
                    <td>{{ s.name }}</td>
                    <td>{{ s.price }}</td>
                    <td>{{ s.duration }}</td>
                    <td>{% if s.discount is null  %}
                            None
                        {% else %}
                            {{ s.discount }}
                        {% endif %}
                    </td>
                    <td>{{ s.totalprice }}</td>
                    <td><a href = "{{ 'serviceedit/' ~ s.id }}">Edit</a></td>
                    <td><a href = "{{ 'servicedelete/' ~ s.id }}">Delete</a></td>
                </tr>
            {% endfor %}
                </table>
                <button type="submit" class="btn btn-primary btn-raised">
                    <a  style="color: #FFF; text-decoration: none;" href="{{ 'serviceregistration' }}"> Create new service</a>
                </button>
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %}
{% endblock %}

SP/templates/service/registration.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello!{% endblock %}

{% block body %}
    <div class="main">
        {% if service is defined %}
        {{ form_start(form) }}
        {% if not form.vars.valid %}
            <div class="alert">
                Service name: {{ form_errors(form.name) }}
                Price: {{ form_errors(form.price) }}
                Duration: {{ form_errors(form.duration) }}
                Discount: {{ form_errors(form.discount) }}
                <br>
                <p>Click on the "x" symbol to close the alert message.</p>
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            </div>
        {% endif %}
        Service name*{{ form_widget(form.name) }}
        Price* {{ form_widget(form.price) }}
        Duration* {{ form_widget(form.duration) }}
        Discount {{ form_widget(form.discount) }}
        <button type="submit" class="btn">Add new service</button>
        {{ form_end(form) }}
        {% else %}
        {{ form_start(form) }}
        {% if not form.vars.valid %}
            <div class="alert">
                Service name: {{ form_errors(form.name) }}
                Price: {{ form_errors(form.price) }}
                Duration: {{ form_errors(form.duration) }}
                Discount: {{ form_errors(form.discount) }}
                <br>
                <p>Click on the "x" symbol to close the alert message.</p>
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            </div>
        {% endif %}
        Service name*{{ form_widget(form.name) }}
        Price* {{ form_widget(form.price) }}
        Duration* {{ form_widget(form.duration) }}
        Discount {{ form_widget(form.discount) }}
        <button type="submit" class="btn">Add new service</button>
        {{ form_end(form) }}
        {% endif %}
    </div>
{% endblock %}